source 'https://rubygems.org/'

gem 'pry'
gem 'foreman'
gem 'mechanize'
gem 'activerecord'
gem 'standalone_migrations'
# gem 'sqlite3'
gem 'pg'
gem 'logger'
gem "paperclip", git: "git://github.com/thoughtbot/paperclip.git"
gem 'aws-sdk', '>= 2.0.0'
gem 'dotenv'
gem 'mailgun-ruby', '~>1.0.3', require: 'mailgun'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack'
gem 'puma'
gem 'slack-notifier'
gem 'kaminari', :require => 'kaminari/sinatra'
gem 'padrino-helpers'

